### ISSUE TITLE
Model viewer shows least interesting side

### ISSUE THREAD

**Issue by rkversion** [kartta-labs/reservoir#28]
Reservoir's landing page displays 6 featureless rectangles/polygons – it is hard to tell that those even are buildings, there is no indication that the are 3D models that can be rotated, etc.

**Comment by brandonmayer** [comment]
Initial heuristic for guessing interesting orientation is pushed to head that pushes the camera out in the direction of the side with the most points (as a proxy for computing planar entropy).
